server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rabbit_reliability?serverTimezone=GMT%2B8
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    # 发送者开启 confirm 确认机制
    publisher-confirm-type: correlated
    # 发送者开启 return 确认机制
    publisher-returns: true
    listener:
      simple:
        # 设置消费端手动 ack
        acknowledge-mode: manual
        # 一次处理的消息数量
        prefetch: 2
        # 消费端最大并发数
        max-concurrency: 5
  redis:
    host: localhost
    port: 6379
    password: 123456
mybatis-plus:
  configuration:
    # 打印 sql
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl